### ISSUE TITLE
mult_bonuses are only for damage and movecost

### ISSUE THREAD

**Issue by waveyl** [RedMisao/Cataclysm-DDA-Touhou-Expansion#1]
Others doesn't work such as dodge, speed and so on. And flat_bonuses work.
![image](https://user-images.githubusercontent.com/22638873/224485530-6e9028a6-6fe2-4b24-af16-0df3514c7f8f.png)
No bonus:
![image](https://user-images.githubusercontent.com/22638873/224485928-26290685-25a5-41ef-a170-5f046d8f49e1.png)
mult_bonuses:
![image](https://user-images.githubusercontent.com/22638873/224485875-ad573854-9179-4648-8e29-8a395a983779.png)
flat_bonuses:
![image](https://user-images.githubusercontent.com/22638873/224485852-d05bb870-6cd8-4c80-92c2-a6b64272b225.png)

**Comment by RedMisao** [comment]
Thank you, this was fixed.
