### ISSUE TITLE
Some mutation/cell biology specific fields ported to enchantments

### ISSUE THREAD

**Issue by waveyl** [RedMisao/Cataclysm-DDA-Touhou-Expansion#10]
See DDA#72034 and #72106

**Comment by RedMisao** [comment]
**Currently** should be fixed by 0.9.6.13_ex
However, more fields are being ported so this will most likely break again, until they finish that process

**Comment by waveyl** [comment]
Seems all parts merged

**Comment by RedMisao** [comment]
Fixed

**Comment by RedMisao** [comment]
Fixed
