### ISSUE TITLE
Should it be -0.2 or 0.2?

### ISSUE THREAD

**Issue by waveyl** [RedMisao/Cataclysm-DDA-Touhou-Expansion#11]
Touhou:
![image](https://github.com/RedMisao/Cataclysm-DDA-Touhou-Expansion/assets/22638873/9b3e238b-512c-4c6f-b695-5a7fc49f8819)
DDA repo:
![image](https://github.com/RedMisao/Cataclysm-DDA-Touhou-Expansion/assets/22638873/1e5a73bc-f73c-4220-b0ed-e0d10a21274a)

**Comment by RedMisao** [comment]
Oh yeah, it should be 0.2. Will fix it next patch.

**Comment by RedMisao** [comment]
Updated
