### ISSUE TITLE
Should it be "Mèihuò rénxíng"?

### ISSUE THREAD

**Issue by waveyl** [RedMisao/Cataclysm-DDA-Touhou-Expansion#19]
魅惑(Mèihuò) is a verb, meaning to bewitch with beauty, and 魅力(Mèilì) is a noun, meaning the power to attract people.

**Comment by RedMisao** [comment]
Thank you, I will correct that
(I don't know Chinese, I just threw words at the translator and checked the kanji/hanzi)

**Comment by RedMisao** [comment]
Corrected
