### ISSUE TITLE
Invalid attack vector id

### ISSUE THREAD

**Issue by waveyl** [RedMisao/Cataclysm-DDA-Touhou-Expansion#26]
See https://github.com/CleverRaven/Cataclysm-DDA/pull/73064
and https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/attack_vectors.json

Techniques can't be used with invalid attack vectors

**Comment by RedMisao** [comment]
My bad, gotta update them with the new vector style.

**Comment by RedMisao** [comment]
Should be fixed now (0.9.6.18)
