### ISSUE TITLE
Who should have the KI_strite mutation?

### ISSUE THREAD

**Issue by waveyl** [RedMisao/Cataclysm-DDA-Touhou-Expansion#27]
![image](https://github.com/user-attachments/assets/ccde0fd9-8045-4a25-8037-dc1a704995f8)
The note says Mokou and Meiling, while the code says Mokou and Kasen.
![image](https://github.com/user-attachments/assets/e6ea4ac5-3f31-4ff4-8435-722642ecf44b)

**Comment by RedMisao** [comment]
I was experimenting with Kasen having `KI_STRIKE` or having a different melee combat style altogether. Kasen is not finished atm.

Regarding Meiling ... I don't remember if she should have it or her martial art was enough, I need to check to confirm.

**Comment by RedMisao** [comment]
Found why Meiling's missing it on her professions list. The spell `meiling_tigerrelease` grants her an effect, which grants her the `KI_STRIKE` mutation while it's active.

**Comment by waveyl** [comment]
Thanks for explaining
