### ISSUE TITLE
Energy cost audit, such as Aya's camera, MIB weapon

### ISSUE THREAD

**Issue by waveyl** [RedMisao/Cataclysm-DDA-Touhou-Expansion#32]
refer:
https://github.com/CleverRaven/Cataclysm-DDA/pull/75361
https://github.com/CleverRaven/Cataclysm-DDA/pull/76029
https://github.com/CleverRaven/Cataclysm-DDA/pull/75557
https://github.com/CleverRaven/Cataclysm-DDA/pull/76065
https://github.com/CleverRaven/Cataclysm-DDA/pull/75912

**Comment by RedMisao** [comment]
Should be fixed now (0.9.6.21 & 0.9.6.21_ex)
