### ISSUE TITLE
Version for 0.H stable

### ISSUE THREAD

**Issue by waveyl** [RedMisao/Cataclysm-DDA-Touhou-Expansion#33]
Current version can't run on CDDA stable candidate version, such as https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-0.H-2024-09-08-0454
Create a new branch to keep compatible with candidate version may be helpful if you would like to release 0.H stable

**Comment by RedMisao** [comment]
Yes, I'm aware of this. I'm waiting for 0.H to be released, and then backport everything that can be from the `testing` branch into the `master` branch of the mod.
The 0.H candidate is still being updated with bugfixes and backports.
