### ISSUE TITLE
Invalid trait id "hair_black_medium", "hair_blond_long" and so on

### ISSUE THREAD

**Issue by waveyl** [RedMisao/Cataclysm-DDA-Touhou-Expansion#5]

**Comment by waveyl** [comment]
And rag has removed by DDA#71411

**Comment by RedMisao** [comment]
The new version should fix the invalid trait issue. I think I got confused/forgot about the new appearances after adding them

Also, rags were removed at the base mod

**Comment by waveyl** [comment]
But these traits can't be displayed in game, do you use other mods?

**Comment by RedMisao** [comment]
No, I don't use other mods. These traits are placeholders for when I finally decide to make NPCs, which will use them. Maybe for custom "make your own youkai" professions, but that's a very long term goal, if anything.

**Comment by waveyl** [comment]
Thanks for explaining. But these bald hairstyle looks really strange lol.
